# configs/config_segmentation.yaml
dataset:
  csv_file: "dataset/river.csv"
  root_dir: "dataset"
  rgb_folder: "rgb"
  mask_folder: "mask"
  image_size: [256, 256]

training:
  batch_size: 8
  num_epochs: 10
  learning_rate: 0.0001
  num_workers: 4

model:
  in_channels: 3
  classes: 1
  encoder_weights: "imagenet"
  encoder_name: "timm-mobilenetv3_small_100"

device: "cuda"
log_dir: "logs/training"

