device: "cuda"  # or "cpu"

dataset:
  csv_file: "dataset/river.csv"
  rgb_folder: "dataset/rgb"
  time_window: 7  # Use 7 consecutive images (e.g., one per day) as input sequence

training:
  batch_size: 16
  num_epochs: 50
  learning_rate: 0.001
  num_workers: 4
  log_dir: "logs/training/forecasting"

model:
  type: "GRU"           # Options: "GRU", "TCN", etc.
  cnn_output_size: 128  # Dimension of image features extracted by the CNN
  gru_hidden_size: 64
  gru_num_layers: 2
  output_size: 1        # Predict a single water level value
